templatesource:
  ipxe: https://raw.githubusercontent.com/300481/autorok-systems/master/7b131b06-5268-4ee2-a137-16893dea3738/templates/ipxe
  boot: https://raw.githubusercontent.com/300481/autorok-systems/master/7b131b06-5268-4ee2-a137-16893dea3738/templates/boot
  rke: https://raw.githubusercontent.com/300481/autorok-systems/master/7b131b06-5268-4ee2-a137-16893dea3738/templates/rke
  install: https://raw.githubusercontent.com/300481/autorok-systems/master/7b131b06-5268-4ee2-a137-16893dea3738/templates/install
clustername: cluster